### ISSUE TITLE
Help message is misleading

### ISSUE THREAD

**Issue by karcaw** [cwru-rcci/dug#1]
https://github.com/cwru-rcci/dug/blob/5daed424f07068bc73b5803552de8124b9abc851/dug.c#L1266

This line really should say `--help`, not `-h`, as the `-h` is for getting human readable sizes

**Comment by many-states** [comment]
Thanks for catching that. We will get it corrected.

**Comment by many-states** [comment]
This has been resolved by #[58512d](https://github.com/cwru-rcci/dug/commit/58512d1acacbb81869b95a0015e93f9b83bebbc8) and will be included in the next release. Thank you for pointing it out.
